SPOOL 101_BDL_ALTER_OGGETTO_ORIGINALE_ROLLBACK.log

SET DEFINE OFF;
SET TIMING ON;
SET TIME ON;
SET ECHO ON;
SET SQLBL ON;
SHOW ERROR;

alter table bdl_oggetto_originale drop column fl_doppia_pagina;
alter table bdl_oggetto_originale drop column segnatura;



  CREATE OR REPLACE FORCE VIEW "V_OGGETTI" ("D_CD_DIGITALIZZATORE", "D_DN_NOME", "I_CD_ISTITUTO", "I_DN_NOME", "P_CD_PROGETTO", "P_DN_TITOLO", "P_DS_STATO", "C_CD_COLLEZIONE", "C_DN_TITOLO", "O_CD_OGGETTO_ORIGINALE", "O_DN_TITOLO", "O_DN_TITOLO_FE", "O_DN_TITOLO_SUP", "O_CD_OGGETTO_ORIGINALE_SUP", "O_FL_OGGETTO_SUPERIORE", "O_NR_OGGETTI_INFERIORI", "T_CD_TIPO_OGGETTO", "T_DN_NOME", "O_FL_OGGETTO_DIGITALE", "O_FL_CORREZIONE", "O_DS_NOTA_CORREZIONE", "O_FL_ANOMALIA_IMMAGINI", "O_DS_LOG_ANOMALIA", "O_DS_STATO", "O_DS_NOTE_NON_VALIDAZIONE", "O_DS_NOTE_NON_PUBBLICAZIONE", "O_NR_IMMAGINI_PREVISTE", "O_NR_IMMAGINI_DIGITALIZZATE", "O_DS_CONTENUTISTICA", "O_DS_FISICA", "O_CD_LIVELLO_BIBLIO", "O_DS_LIVELLO_BIBLIO", "O_CD_SOGGETTO", "O_DS_SOGGETTO", "O_CD_AUTORE", "O_DS_AUTORE", "O_CD_QUALIFICA_AUTORE", "O_DS_QUALIFICA_AUTORE", "O_CD_AUTORE_SEC", "O_DS_AUTORE_SEC", "O_CD_QUALIFICA_AUTORE_SEC", "O_DS_QUALIFICA_AUTORE_SEC", "O_CD_EDITORE", "O_DS_EDITORE", "O_CD_LINGUA", "O_DS_LINGUA", "O_CD_TIPO_IDENTIFICATIVO", "O_DS_TIPO_IDENTIFICATIVO", "O_CD_IDENTIFICATIVO", "O_CD_IDENTIFICATIVO_ISBN", "O_CD_IDENTIFICATIVO_ISSN", "O_DN_LUOGO_PUBBLICAZIONE", "O_CD_QUALIFICATORE_DATA", "O_DS_QUALIFICATORE_DATA", "O_DS_DATA", "O_DS_NOTE", "O_CD_SUPPORTO", "O_DS_SUPPORTO", "O_CD_TECNICA_GRAFICA", "O_DS_TECNICA_GRAFICA", "O_CD_TIPO_GRAFICA", "O_DS_TIPO_GRAFICA", "O_DS_SCALA", "O_DS_PROIEZIONE", "O_DS_COORDINATE", "O_CD_SOGGETTO_PROD", "O_DS_SOGGETTO_PROD", "O_CD_CONTESTO_ARCH", "O_DS_CONTESTO_ARCH", "O_CD_TIPO_ARCHIVIO", "O_DS_TIPO_ARCHIVIO", "O_DS_LINK_CATALOGO", "O_DS_DIRITTI", "O_DS_ALTREINFO", "O_DS_STATO4MONITOR", "O_FL_ISCRITICO", "O_DS_NOTACRITICO", "O_DT_PUBBLICATOIL", "O_NR_RILEVANZA", "O_FL_PDF_MULTIPAGINA", "O_CD_WORK_FILESYSTEM", "O_FL_RICERCA_OCR", "COV_CD_IMMAGINE", "COV_DN_NOME_IMMAGINE", "COV_NR_PX_LARGHEZZA_THUMB", "COV_NR_PX_ALTEZZA_THUMB", "COV_NR_PX_LARGHEZZA_READER", "COV_NR_PX_ALTEZZA_READER", "COV_NR_PX_LARGHEZZA_ZOOM", "COV_NR_PX_ALTEZZA_ZOOM") AS 
  SELECT  

DIGITALIZZATORE.CD_ENTE D_CD_DIGITALIZZATORE,
DIGITALIZZATORE.DN_NOME D_DN_NOME, 

ISTITUTO.CD_ENTE I_CD_ISTITUTO, 
ISTITUTO.DN_NOME I_DN_NOME, 

BDL_PROGETTO.CD_PROGETTO P_CD_PROGETTO, 
BDL_PROGETTO.DN_TITOLO P_DN_TITOLO, 
BDL_PROGETTO.DS_STATO P_DS_STATO, 

BDL_COLLEZIONE.CD_COLLEZIONE C_CD_COLLEZIONE, 
BDL_COLLEZIONE.DN_TITOLO C_DN_TITOLO, 

BDL_OGGETTO_ORIGINALE.CD_OGGETTO_ORIGINALE O_CD_OGGETTO_ORIGINALE, 
BDL_OGGETTO_ORIGINALE.DN_TITOLO O_DN_TITOLO, 
BDL_OGGETTO_ORIGINALE.DN_TITOLO_FE O_DN_TITOLO_FE, 
TITOLOSUP.DN_TITOLO O_DN_TITOLO_SUP, 
TITOLOSUP.CD_OGGETTO_ORIGINALE O_CD_OGGETTO_ORIGINALE_SUP, 
BDL_OGGETTO_ORIGINALE.FL_OGGETTO_SUPERIORE O_FL_OGGETTO_SUPERIORE, 
BDL_OGGETTO_ORIGINALE.NR_OGGETTI_INFERIORI O_NR_OGGETTI_INFERIORI, 
BDL_TIPO_OGGETTO.CD_TIPO_OGGETTO T_CD_TIPO_OGGETTO, 
BDL_TIPO_OGGETTO.DN_NOME T_DN_NOME, 
BDL_OGGETTO_ORIGINALE.FL_OGGETTO_DIGITALE O_FL_OGGETTO_DIGITALE, 
BDL_OGGETTO_ORIGINALE.FL_CORREZIONE O_FL_CORREZIONE, 
BDL_OGGETTO_ORIGINALE.DS_NOTA_CORREZIONE O_DS_NOTA_CORREZIONE, 
BDL_OGGETTO_ORIGINALE.FL_ANOMALIA_IMMAGINI O_FL_ANOMALIA_IMMAGINI, 
BDL_OGGETTO_ORIGINALE.DS_LOG_ANOMALIA O_DS_LOG_ANOMALIA, 
BDL_OGGETTO_ORIGINALE.DS_STATO O_DS_STATO, 
BDL_OGGETTO_ORIGINALE.DS_NOTE_NON_VALIDAZIONE O_DS_NOTE_NON_VALIDAZIONE, 
BDL_OGGETTO_ORIGINALE.DS_NOTE_NON_PUBBLICAZIONE O_DS_NOTE_NON_PUBBLICAZIONE, 
BDL_OGGETTO_ORIGINALE.NR_IMMAGINI_PREVISTE O_NR_IMMAGINI_PREVISTE, 
BDL_OGGETTO_ORIGINALE.NR_IMMAGINI_DIGITALIZZATE O_NR_IMMAGINI_DIGITALIZZATE,

BDL_OGGETTO_ORIGINALE.DS_CONTENUTISTICA O_DS_CONTENUTISTICA,
BDL_OGGETTO_ORIGINALE.DS_FISICA O_DS_FISICA,
BDL_OGGETTO_ORIGINALE.CD_LIVELLO_BIBLIO O_CD_LIVELLO_BIBLIO,
LIVELLO_BIBLIO.DS_DESCRIZIONE O_DS_LIVELLO_BIBLIO,
BDL_OGGETTO_ORIGINALE.CD_SOGGETTO O_CD_SOGGETTO,
SOGGETTO.DS_DESCRIZIONE O_DS_SOGGETTO,
BDL_OGGETTO_ORIGINALE.CD_AUTORE O_CD_AUTORE,
AUTORE.DS_DESCRIZIONE O_DS_AUTORE,
BDL_OGGETTO_ORIGINALE.CD_QUALIFICA_AUTORE O_CD_QUALIFICA_AUTORE,
QUALIFICA_AUTORE.DS_DESCRIZIONE O_DS_QUALIFICA_AUTORE,
BDL_OGGETTO_ORIGINALE.CD_AUTORE_SEC O_CD_AUTORE_SEC,
AUTORE_SEC.DS_DESCRIZIONE O_DS_AUTORE_SEC,
BDL_OGGETTO_ORIGINALE.CD_QUALIFICA_AUTORE_SEC O_CD_QUALIFICA_AUTORE_SEC,
QUALIFICA_AUTORE_SEC.DS_DESCRIZIONE O_DS_QUALIFICA_AUTORE_SEC,
BDL_OGGETTO_ORIGINALE.CD_EDITORE O_CD_EDITORE,
EDITORE.DS_DESCRIZIONE O_DS_EDITORE,
BDL_OGGETTO_ORIGINALE.CD_LINGUA O_CD_LINGUA,
LINGUA.DS_DESCRIZIONE O_DS_LINGUA,
BDL_OGGETTO_ORIGINALE.CD_TIPO_IDENTIFICATIVO O_CD_TIPO_IDENTIFICATIVO,
TIPO_IDENTIFICATIVO.DS_DESCRIZIONE O_DS_TIPO_IDENTIFICATIVO,
BDL_OGGETTO_ORIGINALE.CD_IDENTIFICATIVO O_CD_IDENTIFICATIVO,
BDL_OGGETTO_ORIGINALE.CD_IDENTIFICATIVO_ISBN O_CD_IDENTIFICATIVO_ISBN,
BDL_OGGETTO_ORIGINALE.CD_IDENTIFICATIVO_ISSN O_CD_IDENTIFICATIVO_ISSN,
BDL_OGGETTO_ORIGINALE.DN_LUOGO_PUBBLICAZIONE O_DN_LUOGO_PUBBLICAZIONE,
BDL_OGGETTO_ORIGINALE.CD_QUALIFICATORE_DATA O_CD_QUALIFICATORE_DATA,
QUALIFICATORE_DATA.DS_DESCRIZIONE O_DS_QUALIFICATORE_DATA,
BDL_OGGETTO_ORIGINALE.DS_DATA O_DS_DATA,
BDL_OGGETTO_ORIGINALE.DS_NOTE O_DS_NOTE,
BDL_OGGETTO_ORIGINALE.CD_SUPPORTO O_CD_SUPPORTO,
SUPPORTO.DS_DESCRIZIONE O_DS_SUPPORTO,
BDL_OGGETTO_ORIGINALE.CD_TECNICA_GRAFICA O_CD_TECNICA_GRAFICA,
TECNICA_GRAFICA.DS_DESCRIZIONE O_DS_TECNICA_GRAFICA,
BDL_OGGETTO_ORIGINALE.CD_TIPO_GRAFICA O_CD_TIPO_GRAFICA,
TIPO_GRAFICA.DS_DESCRIZIONE O_DS_TIPO_GRAFICA,
BDL_OGGETTO_ORIGINALE.DS_SCALA O_DS_SCALA,
BDL_OGGETTO_ORIGINALE.DS_PROIEZIONE O_DS_PROIEZIONE,
BDL_OGGETTO_ORIGINALE.DS_COORDINATE O_DS_COORDINATE,
BDL_OGGETTO_ORIGINALE.CD_SOGGETTO_PROD O_CD_SOGGETTO_PROD,
SOGGETTO_PROD.DS_DESCRIZIONE O_DS_SOGGETTO_PROD,
BDL_OGGETTO_ORIGINALE.CD_CONTESTO_ARCH O_CD_CONTESTO_ARCH,
CONTESTO_ARCH.DS_DESCRIZIONE O_DS_CONTESTO_ARCH,
BDL_OGGETTO_ORIGINALE.CD_TIPO_ARCHIVIO O_CD_TIPO_ARCHIVIO,
TIPO_ARCHIVIO.DS_DESCRIZIONE O_DS_TIPO_ARCHIVIO,
BDL_OGGETTO_ORIGINALE.DS_LINK_CATALOGO O_DS_LINK_CATALOGO,
BDL_OGGETTO_ORIGINALE.DS_DIRITTI O_DS_DIRITTI,
BDL_OGGETTO_ORIGINALE.DS_ALTREINFO O_DS_ALTREINFO,
BDL_OGGETTO_ORIGINALE.DS_STATO || (
	CASE BDL_OGGETTO_ORIGINALE.DS_STATO 
		WHEN 'incatalogazione' THEN (
			CASE BDL_OGGETTO_ORIGINALE.FL_ANOMALIA_IMMAGINI 
				WHEN 'T' 
					THEN '|flAnomaliaImmagini' 
				ELSE (
					CASE BDL_OGGETTO_ORIGINALE.FL_CORREZIONE 
						WHEN 'T' 
							THEN '|flCorrezione' 
						ELSE null 
					END
				) 
			END
		)
		WHEN 'catalogato' THEN (
			CASE BDL_OGGETTO_ORIGINALE.FL_ANOMALIA_IMMAGINI 
				WHEN 'T' 
					THEN '|flAnomaliaImmagini' 
				ELSE (
					CASE BDL_OGGETTO_ORIGINALE.FL_CORREZIONE 
						WHEN 'T' 
							THEN '|flCorrezione' 
						ELSE null 
					END
				) 
			END
		)
	END
) AS O_DS_STATO4MONITOR,
(
	CASE BDL_OGGETTO_ORIGINALE.DS_STATO 
		WHEN 'rifiutato' 
			THEN 'T' 
		WHEN 'nonvalidato' 
			THEN 'T' 
		WHEN 'nonpubblicato' 
			THEN 'T' 
		WHEN 'incatalogazione' THEN (
			CASE BDL_OGGETTO_ORIGINALE.FL_CORREZIONE 
				WHEN 'T' 
					THEN 'T' 
				ELSE (
					CASE BDL_OGGETTO_ORIGINALE.FL_ANOMALIA_IMMAGINI 
						WHEN 'T' 
							THEN 'T' 
						ELSE 
							'F'
					END	
				)
			END
		)
		WHEN 'catalogato' THEN (
			CASE BDL_OGGETTO_ORIGINALE.FL_CORREZIONE 
				WHEN 'T' 
					THEN 'T' 
				ELSE (
					CASE BDL_OGGETTO_ORIGINALE.FL_ANOMALIA_IMMAGINI 
						WHEN 'T' 
							THEN 'T' 
						ELSE 
							'F'
					END	
				)
			END
		)
		ELSE 'F'
	END
) AS O_FL_ISCRITICO,
(
    CASE BDL_OGGETTO_ORIGINALE.DS_STATO 
        WHEN 'nonvalidato' 
            THEN BDL_OGGETTO_ORIGINALE.DS_NOTE_NON_VALIDAZIONE
        WHEN 'nonpubblicato' 
            THEN BDL_OGGETTO_ORIGINALE.DS_NOTE_NON_PUBBLICAZIONE
        WHEN 'incatalogazione' THEN (
            CASE BDL_OGGETTO_ORIGINALE.FL_CORREZIONE 
                WHEN 'T' 
                    THEN BDL_OGGETTO_ORIGINALE.DS_NOTA_CORREZIONE
                ELSE (
                    CASE BDL_OGGETTO_ORIGINALE.FL_ANOMALIA_IMMAGINI 
                        WHEN 'T' 
                            THEN BDL_OGGETTO_ORIGINALE.DS_LOG_ANOMALIA 
                        ELSE 
                            ''
                    END    
                )
            END
        )
        WHEN 'catalogato' THEN (
            CASE BDL_OGGETTO_ORIGINALE.FL_CORREZIONE 
                WHEN 'T' 
                    THEN BDL_OGGETTO_ORIGINALE.DS_NOTA_CORREZIONE
                ELSE (
                    CASE BDL_OGGETTO_ORIGINALE.FL_ANOMALIA_IMMAGINI 
                        WHEN 'T' 
                            THEN BDL_OGGETTO_ORIGINALE.DS_LOG_ANOMALIA 
                        ELSE 
                            ''
                    END    
                )
            END
        ) 
        ELSE (
            null
        )
    END
) AS O_DS_NOTACRITICO,
BDL_OGGETTO_ORIGINALE.DT_PUBBLICATOIL O_DT_PUBBLICATOIL,
BDL_OGGETTO_ORIGINALE.NR_RILEVANZA O_NR_RILEVANZA,
BDL_OGGETTO_ORIGINALE.FL_PDF_MULTIPAGINA O_FL_PDF_MULTIPAGINA,
BDL_OGGETTO_ORIGINALE.CD_WORK_FILESYSTEM O_CD_WORK_FILESYSTEM,
BDL_OGGETTO_ORIGINALE.FL_RICERCA_OCR O_FL_RICERCA_OCR,	
IMMAGINE.CD_IMMAGINE COV_CD_IMMAGINE,
IMMAGINE.DN_NOME_IMMAGINE COV_DN_NOME_IMMAGINE,
IMMAGINE.NR_PX_LARGHEZZA_THUMB COV_NR_PX_LARGHEZZA_THUMB,
IMMAGINE.NR_PX_ALTEZZA_THUMB COV_NR_PX_ALTEZZA_THUMB,
IMMAGINE.NR_PX_LARGHEZZA_READER COV_NR_PX_LARGHEZZA_READER,
IMMAGINE.NR_PX_ALTEZZA_READER COV_NR_PX_ALTEZZA_READER,
IMMAGINE.NR_PX_LARGHEZZA_ZOOM COV_NR_PX_LARGHEZZA_ZOOM,
IMMAGINE.NR_PX_ALTEZZA_ZOOM COV_NR_PX_ALTEZZA_ZOOM

FROM BDL_OGGETTO_ORIGINALE 
LEFT JOIN BDL_TIPO_OGGETTO ON BDL_OGGETTO_ORIGINALE.CD_TIPO_OGGETTO=BDL_TIPO_OGGETTO.CD_TIPO_OGGETTO
LEFT JOIN BDL_COLLEZIONE ON BDL_OGGETTO_ORIGINALE.CD_COLLEZIONE=BDL_COLLEZIONE.CD_COLLEZIONE
LEFT JOIN BDL_PROGETTO ON BDL_COLLEZIONE.CD_PROGETTO=BDL_PROGETTO.CD_PROGETTO
LEFT JOIN BDL_ENTE ISTITUTO ON ISTITUTO.CD_ENTE=BDL_PROGETTO.CD_ENTE
LEFT JOIN BDL_ENTE DIGITALIZZATORE ON DIGITALIZZATORE.CD_ENTE=ISTITUTO.CD_ENTE_DIGIT
LEFT JOIN BDL_OGGETTO_ORIGINALE TITOLOSUP ON TITOLOSUP.CD_OGGETTO_ORIGINALE=BDL_OGGETTO_ORIGINALE.CD_OGGETTO_ORIGINALE_SUP
LEFT JOIN BDL_LIVELLO_BIBLIO LIVELLO_BIBLIO ON LIVELLO_BIBLIO.CD_LIVELLO_BIBLIO=BDL_OGGETTO_ORIGINALE.CD_LIVELLO_BIBLIO
LEFT JOIN BDL_SOGGETTO SOGGETTO ON SOGGETTO.CD_SOGGETTO=BDL_OGGETTO_ORIGINALE.CD_SOGGETTO
LEFT JOIN BDL_AUTORE AUTORE ON AUTORE.CD_AUTORE=BDL_OGGETTO_ORIGINALE.CD_AUTORE
LEFT JOIN BDL_QUALIFICA_AUTORE QUALIFICA_AUTORE ON QUALIFICA_AUTORE.CD_QUALIFICA_AUTORE=BDL_OGGETTO_ORIGINALE.CD_QUALIFICA_AUTORE
LEFT JOIN BDL_AUTORE AUTORE_SEC ON AUTORE_SEC.CD_AUTORE=BDL_OGGETTO_ORIGINALE.CD_AUTORE_SEC
LEFT JOIN BDL_QUALIFICA_AUTORE QUALIFICA_AUTORE_SEC ON QUALIFICA_AUTORE_SEC.CD_QUALIFICA_AUTORE=BDL_OGGETTO_ORIGINALE.CD_QUALIFICA_AUTORE_SEC
LEFT JOIN BDL_EDITORE EDITORE ON EDITORE.CD_EDITORE=BDL_OGGETTO_ORIGINALE.CD_EDITORE
LEFT JOIN BDL_LINGUA LINGUA ON LINGUA.CD_LINGUA=BDL_OGGETTO_ORIGINALE.CD_LINGUA
LEFT JOIN BDL_TIPO_IDENTIFICATIVO TIPO_IDENTIFICATIVO ON TIPO_IDENTIFICATIVO.CD_TIPO_IDENTIFICATIVO=BDL_OGGETTO_ORIGINALE.CD_TIPO_IDENTIFICATIVO
LEFT JOIN BDL_QUALIFICATORE_DATA QUALIFICATORE_DATA ON QUALIFICATORE_DATA.CD_QUALIFICATORE_DATA=BDL_OGGETTO_ORIGINALE.CD_QUALIFICATORE_DATA
LEFT JOIN BDL_SUPPORTO SUPPORTO ON SUPPORTO.CD_SUPPORTO=BDL_OGGETTO_ORIGINALE.CD_SUPPORTO
LEFT JOIN BDL_TECNICA_GRAFICA TECNICA_GRAFICA ON TECNICA_GRAFICA.CD_TECNICA_GRAFICA=BDL_OGGETTO_ORIGINALE.CD_TECNICA_GRAFICA
LEFT JOIN BDL_TIPO_GRAFICA TIPO_GRAFICA ON TIPO_GRAFICA.CD_TIPO_GRAFICA=BDL_OGGETTO_ORIGINALE.CD_TIPO_GRAFICA
LEFT JOIN BDL_SOGGETTO_PROD SOGGETTO_PROD ON SOGGETTO_PROD.CD_SOGGETTO_PROD=BDL_OGGETTO_ORIGINALE.CD_SOGGETTO_PROD
LEFT JOIN BDL_CONTESTO_ARCH CONTESTO_ARCH ON CONTESTO_ARCH.CD_CONTESTO_ARCH=BDL_OGGETTO_ORIGINALE.CD_CONTESTO_ARCH
LEFT JOIN BDL_TIPO_ARCHIVIO TIPO_ARCHIVIO ON TIPO_ARCHIVIO.CD_TIPO_ARCHIVIO=BDL_OGGETTO_ORIGINALE.CD_TIPO_ARCHIVIO
LEFT JOIN BDL_IMMAGINE IMMAGINE ON IMMAGINE.CD_OGGETTO_ORIGINALE=BDL_OGGETTO_ORIGINALE.CD_OGGETTO_ORIGINALE AND IMMAGINE.FL_PRINCIPALE='T';
/

SPOOL OFF;