package it.lispa.bdl.commons.domain;

import static javax.persistence.GenerationType.SEQUENCE;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * BdlCollezione generated by hbm2java.
 */
@Entity
@Table(name = "BDL_COLLEZIONE")
public class BdlCollezione extends BdlDomainBase implements java.io.Serializable {

	/** La Costante serialVersionUID. */
	private static final long serialVersionUID = -4795866998284568695L;
	
	/** codice collezione. */
	private BigDecimal cdCollezione;
	
	/** codice progetto. */
	private BigDecimal cdProgetto;
	
	/** denominazione titolo. */
	private String dnTitolo;
	
	/** descrizione descrizione it. */
	private String dsDescrizioneIt;
	
	/** descrizione descrizione en. */
	private String dsDescrizioneEn;
	
	/** descrizione diritti. */
	private String dsDiritti;
	
	/** descrizione ambito disciplinare. */
	private String dsAmbitoDisciplinare;
	
	/** descrizione copertura geografica. */
	private String dsCoperturaGeografica;
	
	/** descrizione periodo. */
	private String dsPeriodo;
	
	/** descrizione anno ogg antico. */
	private String dsAnnoOggAntico;
	
	/** descrizione anno ogg recente. */
	private String dsAnnoOggRecente;
	
	/**
	 * Istanzia un nuovo bdl collezione.
	 */
	public BdlCollezione() {
	}

	/**
	 * Istanzia un nuovo bdl collezione.
	 *
	 * @param cdProgetto  codice progetto
	 * @param dnTitolo  denominazione titolo
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 */
	public BdlCollezione(BigDecimal cdProgetto,
			String dnTitolo, String dsCreatoda, Date dtCreatoil) {
		this.cdProgetto = cdProgetto;
		this.dnTitolo = dnTitolo;
		this.dsCreatoda = dsCreatoda;
		this.dtCreatoil = dtCreatoil;
	}

	/**
	 * Istanzia un nuovo bdl collezione.
	 *
	 * @param cdCollezione  codice collezione
	 * @param cdProgetto  codice progetto
	 * @param dnTitolo  denominazione titolo
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 */
	public BdlCollezione(BigDecimal cdCollezione, BigDecimal cdProgetto,
			String dnTitolo, String dsCreatoda, Date dtCreatoil) {
		this.cdCollezione = cdCollezione;
		this.cdProgetto = cdProgetto;
		this.dnTitolo = dnTitolo;
		this.dsCreatoda = dsCreatoda;
		this.dtCreatoil = dtCreatoil;
	}

	/**
	 * Istanzia un nuovo bdl collezione.
	 *
	 * @param cdCollezione  codice collezione
	 * @param cdProgetto  codice progetto
	 * @param dnTitolo  denominazione titolo
	 * @param dsDescrizioneIt  descrizione descrizione it
	 * @param dsDescrizioneEn  descrizione descrizione en
	 * @param dsDiritti  descrizione diritti
	 * @param dsAmbitoDisciplinare  descrizione ambito disciplinare
	 * @param dsCoperturaGeografica  descrizione copertura geografica
	 * @param dsPeriodo  descrizione periodo
	 * @param dsAnnoOggAntico  descrizione anno ogg antico
	 * @param dsAnnoOggRecente  descrizione anno ogg recente
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 * @param dsModificatoda  descrizione modificatoda
	 * @param dtModificatoil  data modificatoil
	 */
	public BdlCollezione(BigDecimal cdCollezione, BigDecimal cdProgetto,
			String dnTitolo, String dsDescrizioneIt, String dsDescrizioneEn,
			String dsDiritti, String dsAmbitoDisciplinare,
			String dsCoperturaGeografica, String dsPeriodo,
			String dsAnnoOggAntico, String dsAnnoOggRecente, String dsCreatoda,
			Date dtCreatoil, String dsModificatoda, Date dtModificatoil) {
		this.cdCollezione = cdCollezione;
		this.cdProgetto = cdProgetto;
		this.dnTitolo = dnTitolo;
		this.dsDescrizioneIt = dsDescrizioneIt;
		this.dsDescrizioneEn = dsDescrizioneEn;
		this.dsDiritti = dsDiritti;
		this.dsAmbitoDisciplinare = dsAmbitoDisciplinare;
		this.dsCoperturaGeografica = dsCoperturaGeografica;
		this.dsPeriodo = dsPeriodo;
		this.dsAnnoOggAntico = dsAnnoOggAntico;
		this.dsAnnoOggRecente = dsAnnoOggRecente;
		this.dsCreatoda = dsCreatoda;
		this.dtCreatoil = dtCreatoil;
		this.dsModificatoda = dsModificatoda;
		this.dtModificatoil = dtModificatoil;
	}
	
	/**
	 * Istanzia un nuovo bdl collezione.
	 *
	 * @param dnTitolo  denominazione titolo
	 * @param dsDescrizioneIt  descrizione descrizione it
	 * @param dsDescrizioneEn  descrizione descrizione en
	 * @param dsDiritti  descrizione diritti
	 * @param dsAmbitoDisciplinare  descrizione ambito disciplinare
	 * @param dsCoperturaGeografica  descrizione copertura geografica
	 * @param dsPeriodo  descrizione periodo
	 * @param dsAnnoOggAntico  descrizione anno ogg antico
	 * @param dsAnnoOggRecente  descrizione anno ogg recente
	 */
	public BdlCollezione(
			String dnTitolo, 
			String dsDescrizioneIt, 
			String dsDescrizioneEn,
			String dsDiritti, 
			String dsAmbitoDisciplinare,
			String dsCoperturaGeografica, 
			String dsPeriodo,
			String dsAnnoOggAntico, 
			String dsAnnoOggRecente
	) {
		this.dnTitolo = dnTitolo;
		this.dsDescrizioneIt = dsDescrizioneIt;
		this.dsDescrizioneEn = dsDescrizioneEn;
		this.dsDiritti = dsDiritti;
		this.dsAmbitoDisciplinare = dsAmbitoDisciplinare;
		this.dsCoperturaGeografica = dsCoperturaGeografica;
		this.dsPeriodo = dsPeriodo;
		this.dsAnnoOggAntico = dsAnnoOggAntico;
		this.dsAnnoOggRecente = dsAnnoOggRecente;
	}

	/**
	 * Legge codice collezione.
	 *
	 * @return the codice collezione
	 */
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator="BDL_COLLEZIONE_seqgen")
	@SequenceGenerator(name="BDL_COLLEZIONE_seqgen", sequenceName="BDL_COLLEZIONE_SEQ", allocationSize=1)
	@Column(name = "CD_COLLEZIONE", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCdCollezione() {
		return this.cdCollezione;
	}

	/**
	 * Imposta codice collezione.
	 *
	 * @param cdCollezione the new codice collezione
	 */
	public void setCdCollezione(BigDecimal cdCollezione) {
		this.cdCollezione = cdCollezione;
	}

	/**
	 * Legge codice progetto.
	 *
	 * @return the codice progetto
	 */
	@Column(name = "CD_PROGETTO", nullable = false, precision = 31, scale = 0)
	public BigDecimal getCdProgetto() {
		return this.cdProgetto;
	}

	/**
	 * Imposta codice progetto.
	 *
	 * @param cdProgetto the new codice progetto
	 */
	public void setCdProgetto(BigDecimal cdProgetto) {
		this.cdProgetto = cdProgetto;
	}

	/**
	 * Legge denominazione titolo.
	 *
	 * @return the denominazione titolo
	 */
	@Column(name = "DN_TITOLO", nullable = false, length = 100)
	public String getDnTitolo() {
		return this.dnTitolo;
	}

	/**
	 * Imposta denominazione titolo.
	 *
	 * @param dnTitolo the new denominazione titolo
	 */
	public void setDnTitolo(String dnTitolo) {
		this.dnTitolo = dnTitolo;
	}

	/**
	 * Legge descrizione descrizione it.
	 *
	 * @return the descrizione descrizione it
	 */
	@Column(name = "DS_DESCRIZIONE_IT", length = 1000)
	public String getDsDescrizioneIt() {
		return this.dsDescrizioneIt;
	}

	/**
	 * Imposta descrizione descrizione it.
	 *
	 * @param dsDescrizioneIt the new descrizione descrizione it
	 */
	public void setDsDescrizioneIt(String dsDescrizioneIt) {
		this.dsDescrizioneIt = dsDescrizioneIt;
	}

	/**
	 * Legge descrizione descrizione en.
	 *
	 * @return the descrizione descrizione en
	 */
	@Column(name = "DS_DESCRIZIONE_EN", length = 1000)
	public String getDsDescrizioneEn() {
		return this.dsDescrizioneEn;
	}

	/**
	 * Imposta descrizione descrizione en.
	 *
	 * @param dsDescrizioneEn the new descrizione descrizione en
	 */
	public void setDsDescrizioneEn(String dsDescrizioneEn) {
		this.dsDescrizioneEn = dsDescrizioneEn;
	}

	/**
	 * Legge descrizione diritti.
	 *
	 * @return the descrizione diritti
	 */
	@Column(name = "DS_DIRITTI", length = 250)
	public String getDsDiritti() {
		return this.dsDiritti;
	}

	/**
	 * Imposta descrizione diritti.
	 *
	 * @param dsDiritti the new descrizione diritti
	 */
	public void setDsDiritti(String dsDiritti) {
		this.dsDiritti = dsDiritti;
	}

	/**
	 * Legge descrizione ambito disciplinare.
	 *
	 * @return the descrizione ambito disciplinare
	 */
	@Column(name = "DS_AMBITO_DISCIPLINARE", length = 250)
	public String getDsAmbitoDisciplinare() {
		return this.dsAmbitoDisciplinare;
	}

	/**
	 * Imposta descrizione ambito disciplinare.
	 *
	 * @param dsAmbitoDisciplinare the new descrizione ambito disciplinare
	 */
	public void setDsAmbitoDisciplinare(String dsAmbitoDisciplinare) {
		this.dsAmbitoDisciplinare = dsAmbitoDisciplinare;
	}

	/**
	 * Legge descrizione copertura geografica.
	 *
	 * @return the descrizione copertura geografica
	 */
	@Column(name = "DS_COPERTURA_GEOGRAFICA", length = 100)
	public String getDsCoperturaGeografica() {
		return this.dsCoperturaGeografica;
	}

	/**
	 * Imposta descrizione copertura geografica.
	 *
	 * @param dsCoperturaGeografica the new descrizione copertura geografica
	 */
	public void setDsCoperturaGeografica(String dsCoperturaGeografica) {
		this.dsCoperturaGeografica = dsCoperturaGeografica;
	}

	/**
	 * Legge descrizione periodo.
	 *
	 * @return the descrizione periodo
	 */
	@Column(name = "DS_PERIODO", length = 100)
	public String getDsPeriodo() {
		return this.dsPeriodo;
	}

	/**
	 * Imposta descrizione periodo.
	 *
	 * @param dsPeriodo the new descrizione periodo
	 */
	public void setDsPeriodo(String dsPeriodo) {
		this.dsPeriodo = dsPeriodo;
	}

	/**
	 * Legge descrizione anno ogg antico.
	 *
	 * @return the descrizione anno ogg antico
	 */
	@Column(name = "DS_ANNO_OGG_ANTICO", length = 4)
	public String getDsAnnoOggAntico() {
		return this.dsAnnoOggAntico;
	}

	/**
	 * Imposta descrizione anno ogg antico.
	 *
	 * @param dsAnnoOggAntico the new descrizione anno ogg antico
	 */
	public void setDsAnnoOggAntico(String dsAnnoOggAntico) {
		this.dsAnnoOggAntico = dsAnnoOggAntico;
	}

	/**
	 * Legge descrizione anno ogg recente.
	 *
	 * @return the descrizione anno ogg recente
	 */
	@Column(name = "DS_ANNO_OGG_RECENTE", length = 4)
	public String getDsAnnoOggRecente() {
		return this.dsAnnoOggRecente;
	}

	/**
	 * Imposta descrizione anno ogg recente.
	 *
	 * @param dsAnnoOggRecente the new descrizione anno ogg recente
	 */
	public void setDsAnnoOggRecente(String dsAnnoOggRecente) {
		this.dsAnnoOggRecente = dsAnnoOggRecente;
	}
}
