package it.lispa.bdl.commons.domain;

// Generated 29-nov-2013 10.47.17 by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.SEQUENCE;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BdlCronologia generated by hbm2java.
 */
@Entity
@Table(name = "BDL_CRONOLOGIA")
public class BdlCronologia implements java.io.Serializable {

	/** La Costante serialVersionUID. */
	private static final long serialVersionUID = 4542773372295568175L;
	
	/** codice cronologia. */
	private BigDecimal cdCronologia;
	
	/** codice oggetto originale. */
	private BigDecimal cdOggettoOriginale;
	
	/** data operazione. */
	private Date dtOperazione;
	
	/** descrizione ruolo. */
	private String dsRuolo;
	
	/** codice codice fiscale. */
	private String cdCodiceFiscale;
	
	/** descrizione descrizione. */
	private String dsDescrizione;

	/**
	 * Istanzia un nuovo bdl cronologia.
	 */
	public BdlCronologia() {
	}

	/**
	 * Istanzia un nuovo bdl cronologia.
	 *
	 * @param cdOggettoOriginale  codice oggetto originale
	 * @param dtOperazione  data operazione
	 * @param dsRuolo  descrizione ruolo
	 * @param cdCodiceFiscale  codice codice fiscale
	 * @param dsDescrizione  descrizione descrizione
	 */
	public BdlCronologia(
			BigDecimal cdOggettoOriginale, Date dtOperazione,
			String dsRuolo, String cdCodiceFiscale, String dsDescrizione) {
		this.cdOggettoOriginale = cdOggettoOriginale;
		this.dtOperazione = dtOperazione;
		this.dsRuolo = dsRuolo;
		this.cdCodiceFiscale = cdCodiceFiscale;
		this.dsDescrizione = dsDescrizione;
	}
	
	/**
	 * Istanzia un nuovo bdl cronologia.
	 *
	 * @param cdCronologia  codice cronologia
	 * @param cdOggettoOriginale  codice oggetto originale
	 * @param dtOperazione  data operazione
	 * @param dsRuolo  descrizione ruolo
	 * @param cdCodiceFiscale  codice codice fiscale
	 * @param dsDescrizione  descrizione descrizione
	 */
	public BdlCronologia(BigDecimal cdCronologia,
			BigDecimal cdOggettoOriginale, Date dtOperazione,
			String dsRuolo, String cdCodiceFiscale, String dsDescrizione) {
		this.cdCronologia = cdCronologia;
		this.cdOggettoOriginale = cdOggettoOriginale;
		this.dtOperazione = dtOperazione;
		this.dsRuolo = dsRuolo;
		this.cdCodiceFiscale = cdCodiceFiscale;
		this.dsDescrizione = dsDescrizione;
	}

	/**
	 * Legge codice cronologia.
	 *
	 * @return the codice cronologia
	 */
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator="BDL_CRONOLOGIA_seqgen")
	@SequenceGenerator(name="BDL_CRONOLOGIA_seqgen", sequenceName="BDL_CRONOLOGIA_SEQ", allocationSize=1)
	@Column(name = "CD_CRONOLOGIA", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCdCronologia() {
		return this.cdCronologia;
	}

	/**
	 * Imposta codice cronologia.
	 *
	 * @param cdCronologia the new codice cronologia
	 */
	public void setCdCronologia(BigDecimal cdCronologia) {
		this.cdCronologia = cdCronologia;
	}

	/**
	 * Legge codice oggetto originale.
	 *
	 * @return the codice oggetto originale
	 */
	@Column(name = "CD_OGGETTO_ORIGINALE", nullable = false, precision = 31, scale = 0)
	public BigDecimal getCdOggettoOriginale() {
		return this.cdOggettoOriginale;
	}

	/**
	 * Imposta codice oggetto originale.
	 *
	 * @param cdOggettoOriginale the new codice oggetto originale
	 */
	public void setCdOggettoOriginale(BigDecimal cdOggettoOriginale) {
		this.cdOggettoOriginale = cdOggettoOriginale;
	}

	/**
	 * Legge data operazione.
	 *
	 * @return the data operazione
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_OPERAZIONE", nullable = false)
	public Date getDtOperazione() {
		return this.dtOperazione;
	}

	/**
	 * Imposta data operazione.
	 *
	 * @param dtOperazione the new data operazione
	 */
	public void setDtOperazione(Date dtOperazione) {
		this.dtOperazione = dtOperazione;
	}

	/**
	 * Legge descrizione ruolo.
	 *
	 * @return the descrizione ruolo
	 */
	@Column(name = "DS_RUOLO", nullable = false, length = 50)
	public String getDsRuolo() {
		return this.dsRuolo;
	}

	/**
	 * Imposta descrizione ruolo.
	 *
	 * @param dsRuolo the new descrizione ruolo
	 */
	public void setDsRuolo(String dsRuolo) {
		this.dsRuolo = dsRuolo;
	}

	/**
	 * Legge codice codice fiscale.
	 *
	 * @return the codice codice fiscale
	 */
	@Column(name = "CD_CODICE_FISCALE", nullable = false, length = 200)
	public String getCdCodiceFiscale() {
		return this.cdCodiceFiscale;
	}

	/**
	 * Imposta codice codice fiscale.
	 *
	 * @param cdCodiceFiscale the new codice codice fiscale
	 */
	public void setCdCodiceFiscale(String cdCodiceFiscale) {
		this.cdCodiceFiscale = cdCodiceFiscale;
	}

	/**
	 * Legge descrizione descrizione.
	 *
	 * @return the descrizione descrizione
	 */
	@Column(name = "DS_DESCRIZIONE", nullable = false, length = 500)
	public String getDsDescrizione() {
		return this.dsDescrizione;
	}

	/**
	 * Imposta descrizione descrizione.
	 *
	 * @param dsDescrizione the new descrizione descrizione
	 */
	public void setDsDescrizione(String dsDescrizione) {
		this.dsDescrizione = dsDescrizione;
	}
}
