package it.lispa.bdl.commons.domain;

import static javax.persistence.GenerationType.SEQUENCE;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * BdlEnte generated by hbm2java.
 */
@Entity
@Table(name = "BDL_ENTE")
public class BdlEnte extends BdlDomainBase implements java.io.Serializable {

	/** La Costante serialVersionUID. */
	private static final long serialVersionUID = 2401572222932479764L;
	
	/** codice ente. */
	private BigDecimal cdEnte;
	
	/** codice ente digit. */
	private BigDecimal cdEnteDigit;
	
	/** denominazione nome. */
	private String dnNome;
	
	/** descrizione indirizzo. */
	private String dsIndirizzo;
	
	/** denominazione comune. */
	private String dnComune;
	
	/** denominazione provincia. */
	private String dnProvincia;
	
	/** descrizione cap. */
	private String dsCap;
	
	/** nr telefono. */
	private String nrTelefono;
	
	/** nr fax. */
	private String nrFax;
	
	/** denominazione email. */
	private String dnEmail;
	
	/** denominazione indirizzo www. */
	private String dnIndirizzoWww;
	
	/** flag classe. */
	private char flClasse;
	
	/**
	 * Istanzia un nuovo bdl ente.
	 */
	public BdlEnte() {
	}

	/**
	 * Istanzia un nuovo bdl ente.
	 *
	 * @param dnNome  denominazione nome
	 * @param dsIndirizzo  descrizione indirizzo
	 * @param dnComune  denominazione comune
	 * @param dnProvincia  denominazione provincia
	 * @param dsCap  descrizione cap
	 * @param nrTelefono  nr telefono
	 * @param nrFax  nr fax
	 * @param dnEmail  denominazione email
	 * @param flClasse  flag classe
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 */
	public BdlEnte(String dnNome, String dsIndirizzo,
			String dnComune, String dnProvincia, String dsCap,
			String nrTelefono, String nrFax, String dnEmail, char flClasse,
			String dsCreatoda, Date dtCreatoil) {
		this.init(dnNome, dsIndirizzo,dnComune, dnProvincia, dsCap,nrTelefono, nrFax, dnEmail, flClasse,dsCreatoda, dtCreatoil);
	}
	
	/**
	 * Istanzia un nuovo bdl ente.
	 *
	 * @param cdEnte  codice ente
	 * @param dnNome  denominazione nome
	 * @param dsIndirizzo  descrizione indirizzo
	 * @param dnComune  denominazione comune
	 * @param dnProvincia  denominazione provincia
	 * @param dsCap  descrizione cap
	 * @param nrTelefono  nr telefono
	 * @param nrFax  nr fax
	 * @param dnEmail  denominazione email
	 * @param flClasse  flag classe
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 */
	public BdlEnte(BigDecimal cdEnte, String dnNome, String dsIndirizzo,
			String dnComune, String dnProvincia, String dsCap,
			String nrTelefono, String nrFax, String dnEmail, char flClasse,
			String dsCreatoda, Date dtCreatoil) {
		this.cdEnte = cdEnte;
		this.init(dnNome, dsIndirizzo,dnComune, dnProvincia, dsCap,nrTelefono, nrFax, dnEmail, flClasse,dsCreatoda, dtCreatoil);
	}
	
	/**
	 * Inizializza.
	 *
	 * @param dnNome  denominazione nome
	 * @param dsIndirizzo  descrizione indirizzo
	 * @param dnComune  denominazione comune
	 * @param dnProvincia  denominazione provincia
	 * @param dsCap  descrizione cap
	 * @param nrTelefono  nr telefono
	 * @param nrFax  nr fax
	 * @param dnEmail  denominazione email
	 * @param flClasse  flag classe
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 */
	private void init(String dnNome, String dsIndirizzo,
			String dnComune, String dnProvincia, String dsCap,
			String nrTelefono, String nrFax, String dnEmail, char flClasse,
			String dsCreatoda, Date dtCreatoil){
		this.dnNome = dnNome;
		this.dsIndirizzo = dsIndirizzo;
		this.dnComune = dnComune;
		this.dnProvincia = dnProvincia;
		this.dsCap = dsCap;
		this.nrTelefono = nrTelefono;
		this.nrFax = nrFax;
		this.dnEmail = dnEmail;
		this.flClasse = flClasse;
		this.dsCreatoda = dsCreatoda;
		this.dtCreatoil = dtCreatoil;
		
	}

	/**
	 * Istanzia un nuovo bdl ente.
	 *
	 * @param cdEnte  codice ente
	 * @param cdEnteDigit  codice ente digit
	 * @param dnNome  denominazione nome
	 * @param dsIndirizzo  descrizione indirizzo
	 * @param dnComune  denominazione comune
	 * @param dnProvincia  denominazione provincia
	 * @param dsCap  descrizione cap
	 * @param nrTelefono  nr telefono
	 * @param nrFax  nr fax
	 * @param dnEmail  denominazione email
	 * @param dnIndirizzoWww  denominazione indirizzo www
	 * @param flClasse  flag classe
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 * @param dsModificatoda  descrizione modificatoda
	 * @param dtModificatoil  data modificatoil
	 */
	public BdlEnte(BigDecimal cdEnte, BigDecimal cdEnteDigit, String dnNome,
			String dsIndirizzo, String dnComune, String dnProvincia,
			String dsCap, String nrTelefono, String nrFax, String dnEmail,
			String dnIndirizzoWww, char flClasse, String dsCreatoda,
			Date dtCreatoil, String dsModificatoda, Date dtModificatoil) {
		this.cdEnte = cdEnte;
		this.cdEnteDigit = cdEnteDigit;
		this.dnNome = dnNome;
		this.dsIndirizzo = dsIndirizzo;
		this.dnComune = dnComune;
		this.dnProvincia = dnProvincia;
		this.dsCap = dsCap;
		this.nrTelefono = nrTelefono;
		this.nrFax = nrFax;
		this.dnEmail = dnEmail;
		this.dnIndirizzoWww = dnIndirizzoWww;
		this.flClasse = flClasse;
		this.dsCreatoda = dsCreatoda;
		this.dtCreatoil = dtCreatoil;
		this.dsModificatoda = dsModificatoda;
		this.dtModificatoil = dtModificatoil;
	}
	
	/**
	 * Legge codice ente.
	 *
	 * @return the codice ente
	 */
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator="BDL_ENTE_seqgen")
	@SequenceGenerator(name="BDL_ENTE_seqgen", sequenceName="BDL_ENTE_SEQ", allocationSize=1)
	@Column(name = "CD_ENTE", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCdEnte() {
		return this.cdEnte;
	}

	/**
	 * Imposta codice ente.
	 *
	 * @param cdEnte the new codice ente
	 */
	public void setCdEnte(BigDecimal cdEnte) {
		this.cdEnte = cdEnte;
	}

	/**
	 * Legge codice ente digit.
	 *
	 * @return the codice ente digit
	 */
	@Column(name = "CD_ENTE_DIGIT", precision = 31, scale = 0)
	public BigDecimal getCdEnteDigit() {
		return this.cdEnteDigit;
	}

	/**
	 * Imposta codice ente digit.
	 *
	 * @param cdEnteDigit the new codice ente digit
	 */
	public void setCdEnteDigit(BigDecimal cdEnteDigit) {
		this.cdEnteDigit = cdEnteDigit;
	}

	/**
	 * Legge denominazione nome.
	 *
	 * @return the denominazione nome
	 */
	@Column(name = "DN_NOME", nullable = false, length = 100)
	public String getDnNome() {
		return this.dnNome;
	}

	/**
	 * Imposta denominazione nome.
	 *
	 * @param dnNome the new denominazione nome
	 */
	public void setDnNome(String dnNome) {
		this.dnNome = dnNome;
	}

	/**
	 * Legge descrizione indirizzo.
	 *
	 * @return the descrizione indirizzo
	 */
	@Column(name = "DS_INDIRIZZO", nullable = false, length = 100)
	public String getDsIndirizzo() {
		return this.dsIndirizzo;
	}

	/**
	 * Imposta descrizione indirizzo.
	 *
	 * @param dsIndirizzo the new descrizione indirizzo
	 */
	public void setDsIndirizzo(String dsIndirizzo) {
		this.dsIndirizzo = dsIndirizzo;
	}

	/**
	 * Legge denominazione comune.
	 *
	 * @return the denominazione comune
	 */
	@Column(name = "DN_COMUNE", nullable = false, length=75)
	public String getDnComune() {
		return this.dnComune;
	}

	/**
	 * Imposta denominazione comune.
	 *
	 * @param dnComune the new denominazione comune
	 */
	public void setDnComune(String dnComune) {
		this.dnComune = dnComune;
	}

	/**
	 * Legge denominazione provincia.
	 *
	 * @return the denominazione provincia
	 */
	@Column(name = "DN_PROVINCIA", nullable = false, length = 2)
	public String getDnProvincia() {
		return this.dnProvincia;
	}

	/**
	 * Imposta denominazione provincia.
	 *
	 * @param dnProvincia the new denominazione provincia
	 */
	public void setDnProvincia(String dnProvincia) {
		this.dnProvincia = dnProvincia;
	}

	/**
	 * Legge descrizione cap.
	 *
	 * @return the descrizione cap
	 */
	@Column(name = "DS_CAP", nullable = false, length = 5)
	public String getDsCap() {
		return this.dsCap;
	}

	/**
	 * Imposta descrizione cap.
	 *
	 * @param dsCap the new descrizione cap
	 */
	public void setDsCap(String dsCap) {
		this.dsCap = dsCap;
	}

	/**
	 * Legge nr telefono.
	 *
	 * @return the nr telefono
	 */
	@Column(name = "NR_TELEFONO", nullable = false, length = 50)
	public String getNrTelefono() {
		return this.nrTelefono;
	}

	/**
	 * Imposta nr telefono.
	 *
	 * @param nrTelefono the new nr telefono
	 */
	public void setNrTelefono(String nrTelefono) {
		this.nrTelefono = nrTelefono;
	}

	/**
	 * Legge nr fax.
	 *
	 * @return the nr fax
	 */
	@Column(name = "NR_FAX", nullable = true, length = 50)
	public String getNrFax() {
		return this.nrFax;
	}

	/**
	 * Imposta nr fax.
	 *
	 * @param nrFax the new nr fax
	 */
	public void setNrFax(String nrFax) {
		this.nrFax = nrFax;
	}

	/**
	 * Legge denominazione email.
	 *
	 * @return the denominazione email
	 */
	@Column(name = "DN_EMAIL", nullable = true, length = 50)
	public String getDnEmail() {
		return this.dnEmail;
	}

	/**
	 * Imposta denominazione email.
	 *
	 * @param dnEmail the new denominazione email
	 */
	public void setDnEmail(String dnEmail) {
		this.dnEmail = dnEmail;
	}

	/**
	 * Legge denominazione indirizzo www.
	 *
	 * @return the denominazione indirizzo www
	 */
	@Column(name = "DN_INDIRIZZO_WWW", length = 100)
	public String getDnIndirizzoWww() {
		return this.dnIndirizzoWww;
	}

	/**
	 * Imposta denominazione indirizzo www.
	 *
	 * @param dnIndirizzoWww the new denominazione indirizzo www
	 */
	public void setDnIndirizzoWww(String dnIndirizzoWww) {
		this.dnIndirizzoWww = dnIndirizzoWww;
	}

	/**
	 * Legge flag classe.
	 *
	 * @return the flag classe
	 */
	@Column(name = "FL_CLASSE", nullable = false, length = 1)
	public char getFlClasse() {
		return this.flClasse;
	}

	/**
	 * Imposta flag classe.
	 *
	 * @param flClasse the new flag classe
	 */
	public void setFlClasse(char flClasse) {
		this.flClasse = flClasse;
	}
}
