package it.lispa.bdl.commons.domain;

import static javax.persistence.GenerationType.SEQUENCE;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * BdlEnte generated by hbm2java.
 */
@Entity
@Table(name = "BDL_ENTE_UTENTE")
public class BdlEnteUtente implements java.io.Serializable {

	/** La Costante serialVersionUID. */
	private static final long serialVersionUID = 5369390250743093137L;
	
	/** codice ente utente. */
	private BigDecimal cdEnteUtente;
	
	/** codice ente. */
	private BigDecimal cdEnte;
	
	/** codice utente. */
	private BigDecimal cdUtente;

	/**
	 * Istanzia un nuovo bdl ente utente.
	 */
	public BdlEnteUtente() {
	}

	/**
	 * Istanzia un nuovo bdl ente utente.
	 *
	 * @param cdEnte  codice ente
	 * @param cdUtente  codice utente
	 */
	public BdlEnteUtente(BigDecimal cdEnte, BigDecimal cdUtente) {
		this.cdEnte = cdEnte;
		this.cdUtente = cdUtente;
	}
	
	/**
	 * Istanzia un nuovo bdl ente utente.
	 *
	 * @param cdEnteUtente  codice ente utente
	 * @param cdEnte  codice ente
	 * @param cdUtente  codice utente
	 */
	public BdlEnteUtente(BigDecimal cdEnteUtente,BigDecimal cdEnte, BigDecimal cdUtente) {
		this.cdEnteUtente = cdEnteUtente;
		this.cdEnte = cdEnte;
		this.cdUtente = cdUtente;
	}
	
	/**
	 * Legge codice ente utente.
	 *
	 * @return the codice ente utente
	 */
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator="BDL_ENTE_UTENTE_seqgen")
	@SequenceGenerator(name="BDL_ENTE_UTENTE_seqgen", sequenceName="BDL_ENTE_UTENTE_SEQ", allocationSize=1)
	@Column(name = "CD_ENTE_UTENTE", nullable = false, precision = 31, scale = 0)
	public BigDecimal getCdEnteUtente() {
		return this.cdEnteUtente;
	}

	/**
	 * Imposta codice ente utente.
	 *
	 * @param cdEnteUtente the new codice ente utente
	 */
	public void setCdEnteUtente(BigDecimal cdEnteUtente) {
		this.cdEnteUtente = cdEnteUtente;
	}
	
	/**
	 * Legge codice ente.
	 *
	 * @return the codice ente
	 */
	@Column(name = "CD_ENTE", nullable = false, precision = 31, scale = 0)
	public BigDecimal getCdEnte() {
		return this.cdEnte;
	}

	/**
	 * Imposta codice ente.
	 *
	 * @param cdEnte the new codice ente
	 */
	public void setCdEnte(BigDecimal cdEnte) {
		this.cdEnte = cdEnte;
	}
	
	/**
	 * Legge codice utente.
	 *
	 * @return the codice utente
	 */
	@Column(name = "CD_UTENTE", nullable = false, precision = 31, scale = 0)
	public BigDecimal getCdUtente() {
		return this.cdUtente;
	}

	/**
	 * Imposta codice utente.
	 *
	 * @param cdUtente the new codice utente
	 */
	public void setCdUtente(BigDecimal cdUtente) {
		this.cdUtente = cdUtente;
	}
}
