package it.lispa.bdl.commons.domain;

import static javax.persistence.GenerationType.SEQUENCE;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * BdlProgetto generated by hbm2java.
 */
@Entity
@Table(name = "BDL_PDF_PAGINA")
public class BdlPdfPagina implements java.io.Serializable {

	/** La Costante serialVersionUID. */
	private static final long serialVersionUID = 3286472829642047219L;

	/** codice pdf pagina. */
	private BigDecimal cdPdfPagina;
	
	/** descrizione pagina. */
	private String dsPagina;	
	
	/** descrizione pagina due. */
	private String dsPaginaDue;	
	
	/** codice oggetto originale. */
	private BigDecimal cdOggettoOriginale;
	
	/** nr pagina. */
	private BigDecimal nrPagina;

	/**
	 * Istanzia un nuovo bdl pdf pagina.
	 */
	public BdlPdfPagina() {
	}

	/**
	 * Istanzia un nuovo bdl pdf pagina.
	 *
	 * @param cdPdfPagina  codice pdf pagina
	 * @param dsPagina  descrizione pagina
	 * @param dsPaginaDue  descrizione pagina due
	 * @param cdOggettoOriginale  codice oggetto originale
	 * @param nrPagina  nr pagina
	 */
	public BdlPdfPagina(BigDecimal cdPdfPagina, 
						String dsPagina, String dsPaginaDue,
						BigDecimal cdOggettoOriginale,
						BigDecimal nrPagina) {
		this.cdPdfPagina = cdPdfPagina;
		this.dsPagina = dsPagina;
		this.dsPaginaDue = dsPaginaDue;
		this.cdOggettoOriginale = cdOggettoOriginale;
		this.nrPagina = nrPagina;
	}
	
	/**
	 * Legge codice pdf pagina.
	 *
	 * @return the codice pdf pagina
	 */
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator="BDL_PDF_PAGINA_seqgen")
	@SequenceGenerator(name="BDL_PDF_PAGINA_seqgen", sequenceName="BDL_PDF_PAGINA_SEQ", allocationSize=1)
	@Column(name = "CD_PDF_PAGINA", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCdPdfPagina() {
		return this.cdPdfPagina;
	}
	
	/**
	 * Imposta codice pdf pagina.
	 *
	 * @param cdPdfPagina the new codice pdf pagina
	 */
	public void setCdPdfPagina(BigDecimal cdPdfPagina) {
		this.cdPdfPagina = cdPdfPagina;
	}

	/**
	 * Legge codice oggetto originale.
	 *
	 * @return the codice oggetto originale
	 */
	@Column(name = "CD_OGGETTO_ORIGINALE", nullable = false, precision = 31, scale = 0)
	public BigDecimal getCdOggettoOriginale() {
		return this.cdOggettoOriginale;
	}
	
	/**
	 * Imposta codice oggetto originale.
	 *
	 * @param cdOggettoOriginale the new codice oggetto originale
	 */
	public void setCdOggettoOriginale(BigDecimal cdOggettoOriginale) {
		this.cdOggettoOriginale = cdOggettoOriginale;
	}

	/**
	 * Legge nr pagina.
	 *
	 * @return the nr pagina
	 */
	@Column(name = "NR_PAGINA", nullable = false, precision = 31, scale = 0)
	public BigDecimal getNrPagina() {
		return this.nrPagina;
	}
	
	/**
	 * Imposta nr pagina.
	 *
	 * @param nrPagina the new nr pagina
	 */
	public void setNrPagina(BigDecimal nrPagina) {
		this.nrPagina = nrPagina;
	}

	/**
	 * Legge descrizione pagina.
	 *
	 * @return the descrizione pagina
	 */
	@Column(name = "DS_PAGINA", nullable = false)
	public String getDsPagina() {
		return dsPagina;
	}
	
	/**
	 * Imposta descrizione pagina.
	 *
	 * @param dsPagina the new descrizione pagina
	 */
	public void setDsPagina(String dsPagina) {
		this.dsPagina = dsPagina;
	}

	/**
	 * Legge descrizione pagina due.
	 *
	 * @return the descrizione pagina due
	 */
	@Column(name = "DS_PAGINA_DUE", nullable = true)
	public String getDsPaginaDue() {
		return dsPaginaDue;
	}
	
	/**
	 * Imposta descrizione pagina due.
	 *
	 * @param dsPaginaDue the new descrizione pagina due
	 */
	public void setDsPaginaDue(String dsPaginaDue) {
		this.dsPaginaDue = dsPaginaDue;
	}
}
