package it.lispa.bdl.commons.domain;

// Generated 29-nov-2013 10.47.17 by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.SEQUENCE;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BdlProgetto generated by hbm2java.
 */
@Entity
@Table(name = "BDL_PROGETTO")
public class BdlProgetto extends BdlDomainBase implements java.io.Serializable {

	/** La Costante serialVersionUID. */
	private static final long serialVersionUID = -1359215423946833930L;
	
	/** codice progetto. */
	private BigDecimal cdProgetto;
	
	/** codice ente. */
	private BigDecimal cdEnte;
	
	/** denominazione titolo. */
	private String dnTitolo;
	
	/** denominazione titolo breve. */
	private String dnTitoloBreve;
	
	/** descrizione descrizione it. */
	private String dsDescrizioneIt;
	
	/** descrizione descrizione en. */
	private String dsDescrizioneEn;
	
	/** data inizio. */
	private Date dtInizio;
	
	/** data conclusione. */
	private Date dtConclusione;
	
	/** descrizione stato. */
	private String dsStato;
	
	/**
	 * Istanzia un nuovo bdl progetto.
	 */
	public BdlProgetto() {
	}

	/**
	 * Istanzia un nuovo bdl progetto.
	 *
	 * @param cdEnte  codice ente
	 * @param dnTitolo  denominazione titolo
	 * @param dsStato  descrizione stato
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 */
	public BdlProgetto(BigDecimal cdEnte, String dnTitolo,
			String dsStato, String dsCreatoda, Date dtCreatoil) {
		this.cdEnte = cdEnte;
		this.dnTitolo = dnTitolo;
		this.dsStato = dsStato;
		this.dsCreatoda = dsCreatoda;
		this.dtCreatoil = dtCreatoil;
	}

	/**
	 * Istanzia un nuovo bdl progetto.
	 *
	 * @param cdProgetto  codice progetto
	 * @param cdEnte  codice ente
	 * @param dnTitolo  denominazione titolo
	 * @param dsStato  descrizione stato
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 */
	public BdlProgetto(BigDecimal cdProgetto, BigDecimal cdEnte, String dnTitolo,
			String dsStato, String dsCreatoda, Date dtCreatoil) {
		this.cdProgetto = cdProgetto;
		this.cdEnte = cdEnte;
		this.dnTitolo = dnTitolo;
		this.dsStato = dsStato;
		this.dsCreatoda = dsCreatoda;
		this.dtCreatoil = dtCreatoil;
	}

	/**
	 * Istanzia un nuovo bdl progetto.
	 *
	 * @param cdProgetto  codice progetto
	 * @param cdEnte  codice ente
	 * @param dnTitolo  denominazione titolo
	 * @param dnTitoloBreve  denominazione titolo breve
	 * @param dsDescrizioneIt  descrizione descrizione it
	 * @param dsDescrizioneEn  descrizione descrizione en
	 * @param dtInizio  data inizio
	 * @param dtConclusione  data conclusione
	 * @param dsStato  descrizione stato
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 * @param dsModificatoda  descrizione modificatoda
	 * @param dtModificatoil  data modificatoil
	 */
	public BdlProgetto(BigDecimal cdProgetto, BigDecimal cdEnte, String dnTitolo,
			String dnTitoloBreve, String dsDescrizioneIt,
			String dsDescrizioneEn, Date dtInizio, Date dtConclusione,
			String dsStato, String dsCreatoda, Date dtCreatoil,
			String dsModificatoda, Date dtModificatoil) {
		this.cdProgetto = cdProgetto;
		this.cdEnte = cdEnte;
		this.dnTitolo = dnTitolo;
		this.dnTitoloBreve = dnTitoloBreve;
		this.dsDescrizioneIt = dsDescrizioneIt;
		this.dsDescrizioneEn = dsDescrizioneEn;
		this.dtInizio = dtInizio;
		this.dtConclusione = dtConclusione;
		this.dsStato = dsStato;
		this.dsCreatoda = dsCreatoda;
		this.dtCreatoil = dtCreatoil;
		this.dsModificatoda = dsModificatoda;
		this.dtModificatoil = dtModificatoil;
	}

	/**
	 * Istanzia un nuovo bdl progetto.
	 *
	 * @param dnTitolo  denominazione titolo
	 * @param dnTitoloBreve  denominazione titolo breve
	 * @param dsDescrizioneIt  descrizione descrizione it
	 * @param dsDescrizioneEn  descrizione descrizione en
	 * @param dtInizio  data inizio
	 * @param dtConclusione  data conclusione
	 */
	public BdlProgetto(
			String dnTitolo,
			String dnTitoloBreve, 
			String dsDescrizioneIt,
			String dsDescrizioneEn, 
			Date dtInizio, 
			Date dtConclusione
	) {
		this.dnTitolo = dnTitolo;
		this.dnTitoloBreve = dnTitoloBreve;
		this.dsDescrizioneIt = dsDescrizioneIt;
		this.dsDescrizioneEn = dsDescrizioneEn;
		this.dtInizio = dtInizio;
		this.dtConclusione = dtConclusione;
	}

	
	/**
	 * Legge codice progetto.
	 *
	 * @return the codice progetto
	 */
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator="BDL_PROGETTO_seqgen")
	@SequenceGenerator(name="BDL_PROGETTO_seqgen", sequenceName="BDL_PROGETTO_SEQ", allocationSize=1)
	@Column(name = "CD_PROGETTO", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCdProgetto() {
		return this.cdProgetto;
	}

	/**
	 * Imposta codice progetto.
	 *
	 * @param cdProgetto the new codice progetto
	 */
	public void setCdProgetto(BigDecimal cdProgetto) {
		this.cdProgetto = cdProgetto;
	}

	/**
	 * Legge codice ente.
	 *
	 * @return the codice ente
	 */
	@Column(name = "CD_ENTE", nullable = false, precision = 31, scale = 0)
	public BigDecimal getCdEnte() {
		return this.cdEnte;
	}

	/**
	 * Imposta codice ente.
	 *
	 * @param cdEnte the new codice ente
	 */
	public void setCdEnte(BigDecimal cdEnte) {
		this.cdEnte = cdEnte;
	}

	/**
	 * Legge denominazione titolo.
	 *
	 * @return the denominazione titolo
	 */
	@Column(name = "DN_TITOLO", nullable = false, length = 100)
	public String getDnTitolo() {
		return this.dnTitolo;
	}

	/**
	 * Imposta denominazione titolo.
	 *
	 * @param dnTitolo the new denominazione titolo
	 */
	public void setDnTitolo(String dnTitolo) {
		this.dnTitolo = dnTitolo;
	}

	/**
	 * Legge denominazione titolo breve.
	 *
	 * @return the denominazione titolo breve
	 */
	@Column(name = "DN_TITOLO_BREVE", length = 50)
	public String getDnTitoloBreve() {
		return this.dnTitoloBreve;
	}

	/**
	 * Imposta denominazione titolo breve.
	 *
	 * @param dnTitoloBreve the new denominazione titolo breve
	 */
	public void setDnTitoloBreve(String dnTitoloBreve) {
		this.dnTitoloBreve = dnTitoloBreve;
	}

	/**
	 * Legge descrizione descrizione it.
	 *
	 * @return the descrizione descrizione it
	 */
	@Column(name = "DS_DESCRIZIONE_IT", length = 1000)
	public String getDsDescrizioneIt() {
		return this.dsDescrizioneIt;
	}

	/**
	 * Imposta descrizione descrizione it.
	 *
	 * @param dsDescrizioneIt the new descrizione descrizione it
	 */
	public void setDsDescrizioneIt(String dsDescrizioneIt) {
		this.dsDescrizioneIt = dsDescrizioneIt;
	}

	/**
	 * Legge descrizione descrizione en.
	 *
	 * @return the descrizione descrizione en
	 */
	@Column(name = "DS_DESCRIZIONE_EN", length = 1000)
	public String getDsDescrizioneEn() {
		return this.dsDescrizioneEn;
	}

	/**
	 * Imposta descrizione descrizione en.
	 *
	 * @param dsDescrizioneEn the new descrizione descrizione en
	 */
	public void setDsDescrizioneEn(String dsDescrizioneEn) {
		this.dsDescrizioneEn = dsDescrizioneEn;
	}

	/**
	 * Legge data inizio.
	 *
	 * @return the data inizio
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_INIZIO")
	public Date getDtInizio() {
		return this.dtInizio;
	}

	/**
	 * Imposta data inizio.
	 *
	 * @param dtInizio the new data inizio
	 */
	public void setDtInizio(Date dtInizio) {
		this.dtInizio = dtInizio;
	}

	/**
	 * Legge data conclusione.
	 *
	 * @return the data conclusione
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_CONCLUSIONE")
	public Date getDtConclusione() {
		return this.dtConclusione;
	}

	/**
	 * Imposta data conclusione.
	 *
	 * @param dtConclusione the new data conclusione
	 */
	public void setDtConclusione(Date dtConclusione) {
		this.dtConclusione = dtConclusione;
	}

	/**
	 * Legge descrizione stato.
	 *
	 * @return the descrizione stato
	 */
	@Column(name = "DS_STATO", nullable = false, length = 30)
	public String getDsStato() {
		return this.dsStato;
	}

	/**
	 * Imposta descrizione stato.
	 *
	 * @param dsStato the new descrizione stato
	 */
	public void setDsStato(String dsStato) {
		this.dsStato = dsStato;
	}
}
