package it.lispa.bdl.commons.domain;

import static javax.persistence.GenerationType.SEQUENCE;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BdlUtente generated by hbm2java.
 */
@Entity
@Table(name = "BDL_QRTZ_BDLJOBS")
public class BdlQrtzBdlJobs implements java.io.Serializable {

	/** La Costante serialVersionUID. */
	private static final long serialVersionUID = 814091483259178632L;

	/** codice bdl jobs. */
	private BigDecimal cdBdlJobs;
	
	/** codice utente. */
	private BigDecimal cdUtente;
	
	/** data start. */
	private Date dtStart;
	
	/** data end. */
	private Date dtEnd;
	
	/** descrizione tipo. */
	private String dsTipo;
	
	/** descrizione esito. */
	private String dsEsito;
	
	/** descrizione input. */
	private String dsInput;
	
	/** descrizione output. */
	private String dsOutput;
	
	/**
	 * Istanzia un nuovo bdl qrtz bdl jobs.
	 */
	public BdlQrtzBdlJobs() {
	}


	/**
	 * Istanzia un nuovo bdl qrtz bdl jobs.
	 *
	 * @param cdBdlJobs  codice bdl jobs
	 * @param cdUtente  codice utente
	 * @param dtStart  data start
	 * @param dtEnd  data end
	 * @param dsTipo  descrizione tipo
	 * @param dsEsito  descrizione esito
	 * @param dsInput  descrizione input
	 * @param dsOutput  descrizione output
	 */
	public BdlQrtzBdlJobs(BigDecimal cdBdlJobs, BigDecimal cdUtente,
			Date dtStart, Date dtEnd, String dsTipo, String dsEsito,
			String dsInput, String dsOutput) {
		super();
		this.cdBdlJobs = cdBdlJobs;
		this.init(cdUtente,dtStart, dtEnd, dsTipo, dsEsito,dsInput, dsOutput);
	}

	/**
	 * Istanzia un nuovo bdl qrtz bdl jobs.
	 *
	 * @param cdUtente  codice utente
	 * @param dtStart  data start
	 * @param dtEnd  data end
	 * @param dsTipo  descrizione tipo
	 * @param dsEsito  descrizione esito
	 * @param dsInput  descrizione input
	 * @param dsOutput  descrizione output
	 */
	public BdlQrtzBdlJobs(BigDecimal cdUtente,
			Date dtStart, Date dtEnd, String dsTipo, String dsEsito,
			String dsInput, String dsOutput) {
		super();
		this.init(cdUtente,dtStart, dtEnd, dsTipo, dsEsito,dsInput, dsOutput);
	}
	
	/**
	 * Inizializza.
	 *
	 * @param cdUtente  codice utente
	 * @param dtStart  data start
	 * @param dtEnd  data end
	 * @param dsTipo  descrizione tipo
	 * @param dsEsito  descrizione esito
	 * @param dsInput  descrizione input
	 * @param dsOutput  descrizione output
	 */
	private void init(BigDecimal cdUtente,
			Date dtStart, Date dtEnd, String dsTipo, String dsEsito,
			String dsInput, String dsOutput){

		this.cdUtente = cdUtente;
		this.dtStart = dtStart;
		this.dtEnd = dtEnd;
		this.dsTipo = dsTipo;
		this.dsEsito = dsEsito;
		this.dsInput = dsInput;
		this.dsOutput = dsOutput;
	}

	/**
	 * Legge codice bdl jobs.
	 *
	 * @return the codice bdl jobs
	 */
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator="BDL_QRTZ_BDLJOBS_seqgen")
	@SequenceGenerator(name="BDL_QRTZ_BDLJOBS_seqgen", sequenceName="BDL_QRTZ_BDLJOBS_SEQ", allocationSize=1)
	@Column(name = "CD_BDLJOBS", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCdBdlJobs() {
		return cdBdlJobs;
	}

	/**
	 * Imposta codice bdl jobs.
	 *
	 * @param cdBdlJobs the new codice bdl jobs
	 */
	public void setCdBdlJobs(BigDecimal cdBdlJobs) {
		this.cdBdlJobs = cdBdlJobs;
	}
	
	/**
	 * Legge codice utente.
	 *
	 * @return the codice utente
	 */
	@Column(name = "CD_UTENTE", nullable = false, precision = 31, scale = 0)
	public BigDecimal getCdUtente() {
		return cdUtente;
	}

	/**
	 * Imposta codice utente.
	 *
	 * @param cdUtente the new codice utente
	 */
	public void setCdUtente(BigDecimal cdUtente) {
		this.cdUtente = cdUtente;
	}

	/**
	 * Legge data start.
	 *
	 * @return the data start
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_START")
	public Date getDtStart() {
		return dtStart;
	}

	/**
	 * Imposta data start.
	 *
	 * @param dtStart the new data start
	 */
	public void setDtStart(Date dtStart) {
		this.dtStart = dtStart;
	}

	/**
	 * Legge data end.
	 *
	 * @return the data end
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_END")
	public Date getDtEnd() {
		return dtEnd;
	}

	/**
	 * Imposta data end.
	 *
	 * @param dtEnd the new data end
	 */
	public void setDtEnd(Date dtEnd) {
		this.dtEnd = dtEnd;
	}	

	/**
	 * Legge descrizione tipo.
	 *
	 * @return the descrizione tipo
	 */
	@Column(name = "DS_TIPO", nullable = false, length = 255)
	public String getDsTipo() {
		return dsTipo;
	}

	/**
	 * Imposta descrizione tipo.
	 *
	 * @param dsTipo the new descrizione tipo
	 */
	public void setDsTipo(String dsTipo) {
		this.dsTipo = dsTipo;
	}

	/**
	 * Legge descrizione esito.
	 *
	 * @return the descrizione esito
	 */
	@Column(name = "DS_ESITO", length = 255)
	public String getDsEsito() {
		return dsEsito;
	}

	/**
	 * Imposta descrizione esito.
	 *
	 * @param dsEsito the new descrizione esito
	 */
	public void setDsEsito(String dsEsito) {
		this.dsEsito = dsEsito;
	}

	/**
	 * Legge descrizione input.
	 *
	 * @return the descrizione input
	 */
	@Column(name = "DS_INPUT", length = 4000)
	public String getDsInput() {
		return dsInput;
	}

	/**
	 * Imposta descrizione input.
	 *
	 * @param dsInput the new descrizione input
	 */
	public void setDsInput(String dsInput) {
		this.dsInput = dsInput;
	}

	/**
	 * Legge descrizione output.
	 *
	 * @return the descrizione output
	 */
	@Column(name = "DS_OUTPUT", length = 4000)
	public String getDsOutput() {
		return dsOutput;
	}

	/**
	 * Imposta descrizione output.
	 *
	 * @param dsOutput the new descrizione output
	 */
	public void setDsOutput(String dsOutput) {
		this.dsOutput = dsOutput;
	}


}
