/* 
 * Copyright 2000-2009 Project.net Inc.
 *
 * This file is part of Project.net.
 * Project.net is free software: you can redistribute it and/or modify it under the terms of 
 * the GNU General Public License as published by the Free Software Foundation, version 3 of the License.
 * 
 * Project.net is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; 
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. 
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with Project.net.
 * If not, see http://www.gnu.org/licenses/gpl-3.0.html
 */
package it.lispa.bdl.commons.domain;

import java.io.Serializable;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import org.apache.commons.lang.builder.EqualsBuilder;
import org.apache.commons.lang.builder.HashCodeBuilder;

/**
 * QrtzTriggerPK generated by hbm2java.
 */
@Embeddable
public class BdlQrtzTriggerPK implements Serializable {

	/** La Costante serialVersionUID. */
	private static final long serialVersionUID = 1684644304263763186L;
	
	/** sched name. */
	private String schedName;
	
	/** trigger name. */
	private String triggerName;
	
	/** trigger group. */
	private String triggerGroup;

	/**
	 * Istanzia un nuovo bdl qrtz trigger pk.
	 */
	public BdlQrtzTriggerPK() {
	}

	/**
	 * Istanzia un nuovo bdl qrtz trigger pk.
	 *
	 * @param schedName  sched name
	 * @param triggerName  trigger name
	 * @param triggerGroup  trigger group
	 */
	public BdlQrtzTriggerPK(String schedName, String triggerName, String triggerGroup) {
		this.schedName = schedName;
		this.triggerName = triggerName;
		this.triggerGroup = triggerGroup;
	}



	/**
	 * Legge sched name.
	 *
	 * @return the sched name
	 */
	@Column(name="SCHED_NAME", nullable=false, length=120)
	public String getSchedName() {
		return schedName;
	}

	/**
	 * Imposta sched name.
	 *
	 * @param schedName the new sched name
	 */
	public void setSchedName(String schedName) {
		this.schedName = schedName;
	}

	/**
	 * Legge trigger name.
	 *
	 * @return the trigger name
	 */
	@Column(name="TRIGGER_NAME", nullable=false, length=200)
	public String getTriggerName() {
		return this.triggerName;
	}

	/**
	 * Imposta trigger name.
	 *
	 * @param triggerName the new trigger name
	 */
	public void setTriggerName(String triggerName) {
		this.triggerName = triggerName;
	}


	/**
	 * Legge trigger group.
	 *
	 * @return the trigger group
	 */
	@Column(name="TRIGGER_GROUP", nullable=false, length=200)
	public String getTriggerGroup() {
		return this.triggerGroup;
	}

	/**
	 * Imposta trigger group.
	 *
	 * @param triggerGroup the new trigger group
	 */
	public void setTriggerGroup(String triggerGroup) {
		this.triggerGroup = triggerGroup;
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#toString()
	 */
	public String toString() {
		return "schedName-"+getSchedName()+"-triggerName-"+getTriggerName()+"-triggerGroup-"+getTriggerGroup();
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	public boolean equals(Object other) {
		if ( (this == other ) ) return true;
		if ( !(other instanceof BdlQrtzTriggerPK) ) return false;
		BdlQrtzTriggerPK castOther = (BdlQrtzTriggerPK) other;
		return new EqualsBuilder()
		.append(this.getSchedName(), castOther.getSchedName())
		.append(this.getTriggerName(), castOther.getTriggerName())
		.append(this.getTriggerGroup(), castOther.getTriggerGroup())
		.isEquals();
	}

	/* (non-Javadoc)
	 * @see java.lang.Object#hashCode()
	 */
	public int hashCode() {
		return new HashCodeBuilder()
		.append(getSchedName())
		.append(getTriggerName())
		.append(getTriggerGroup())
		.toHashCode();
	}

}
