package it.lispa.bdl.commons.domain;

// Generated 29-nov-2013 10.47.17 by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.SEQUENCE;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

/**
 * BdlRuoloDTO generated by hbm2java.
 */
@Entity
@Table(name = "BDL_RUOLO")
public class BdlRuolo extends BdlDomainBase implements java.io.Serializable {

	/** La Costante serialVersionUID. */
	private static final long serialVersionUID = -8258410174882213433L;

	/** codice ruolo. */
	private BigDecimal cdRuolo;
	
	/** denominazione nome. */
	private String dnNome;
	
	/** flag registrabile. */
	private Boolean flRegistrabile;
	
	/**
	 * Istanzia un nuovo bdl ruolo.
	 */
	public BdlRuolo() {
	}

	/**
	 * Istanzia un nuovo bdl ruolo.
	 *
	 * @param dnNome  denominazione nome
	 * @param flRegistrabile  flag registrabile
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 */
	public BdlRuolo(String dnNome, Boolean flRegistrabile, String dsCreatoda, Date dtCreatoil) {
		this.dnNome = dnNome;
		this.flRegistrabile = flRegistrabile;
		this.dsCreatoda = dsCreatoda;
		this.dtCreatoil = dtCreatoil;
	}

	/**
	 * Istanzia un nuovo bdl ruolo.
	 *
	 * @param cdRuolo  codice ruolo
	 * @param dnNome  denominazione nome
	 * @param flRegistrabile  flag registrabile
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 */
	public BdlRuolo(BigDecimal cdRuolo, String dnNome, Boolean flRegistrabile,
			String dsCreatoda, Date dtCreatoil) {
		this.cdRuolo = cdRuolo;
		this.dnNome = dnNome;
		this.flRegistrabile = flRegistrabile;
		this.dsCreatoda = dsCreatoda;
		this.dtCreatoil = dtCreatoil;
	}

	/**
	 * Istanzia un nuovo bdl ruolo.
	 *
	 * @param cdRuolo  codice ruolo
	 * @param dnNome  denominazione nome
	 * @param flRegistrabile  flag registrabile
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 * @param dsModificatoda  descrizione modificatoda
	 * @param dtModificatoil  data modificatoil
	 * @param bdlUtentes  bdl utentes
	 */
	public BdlRuolo(BigDecimal cdRuolo, String dnNome, Boolean flRegistrabile,
			String dsCreatoda, Date dtCreatoil, String dsModificatoda,
			Date dtModificatoil, Set<BdlUtente> bdlUtentes) {
		this.cdRuolo = cdRuolo;
		this.dnNome = dnNome;
		this.flRegistrabile = flRegistrabile;
		this.dsCreatoda = dsCreatoda;
		this.dtCreatoil = dtCreatoil;
		this.dsModificatoda = dsModificatoda;
		this.dtModificatoil = dtModificatoil;
	}

	/**
	 * Legge codice ruolo.
	 *
	 * @return the codice ruolo
	 */
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator="BDL_RUOLO_seqgen")
	@SequenceGenerator(name="BDL_RUOLO_seqgen", sequenceName="BDL_RUOLO_SEQ", allocationSize=1)
	@Column(name = "CD_RUOLO", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCdRuolo() {
		return this.cdRuolo;
	}

	/**
	 * Imposta codice ruolo.
	 *
	 * @param cdRuolo the new codice ruolo
	 */
	public void setCdRuolo(BigDecimal cdRuolo) {
		this.cdRuolo = cdRuolo;
	}

	/**
	 * Legge denominazione nome.
	 *
	 * @return the denominazione nome
	 */
	@Column(name = "DN_NOME", nullable = false, length = 100)
	public String getDnNome() {
		return this.dnNome;
	}

	/**
	 * Imposta denominazione nome.
	 *
	 * @param dnNome the new denominazione nome
	 */
	public void setDnNome(String dnNome) {
		this.dnNome = dnNome;
	}

	/**
	 * Legge flag registrabile.
	 *
	 * @return the flag registrabile
	 */
	@Column(name = "FL_REGISTRABILE", nullable = false)
	@Type(type="true_false")
	public Boolean getFlRegistrabile() {
		return this.flRegistrabile;
	}

	/**
	 * Imposta flag registrabile.
	 *
	 * @param flRegistrabile the new flag registrabile
	 */
	public void setFlRegistrabile(Boolean flRegistrabile) {
		this.flRegistrabile = flRegistrabile;
	}
}
