package it.lispa.bdl.commons.domain;

// Generated 29-nov-2013 10.47.17 by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.SEQUENCE;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * BdlTipoOggetto generated by hbm2java.
 */
@Entity
@Table(name = "BDL_TIPO_OGGETTO")
public class BdlTipoOggetto extends BdlDomainBase implements java.io.Serializable {

	/** La Costante serialVersionUID. */
	private static final long serialVersionUID = 4878111255772901643L;
	
	/** codice tipo oggetto. */
	private BigDecimal cdTipoOggetto;
	
	/** denominazione nome. */
	private String dnNome;
	
	/** descrizione catalogo. */
	private String dsCatalogo;
	
	/** codice catalogo. */
	private String cdCatalogo;
	
	/**
	 * Istanzia un nuovo bdl tipo oggetto.
	 */
	public BdlTipoOggetto() {
	}

	/**
	 * Istanzia un nuovo bdl tipo oggetto.
	 *
	 * @param dnNome  denominazione nome
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 */
	public BdlTipoOggetto(String dnNome, String dsCreatoda, Date dtCreatoil) {
		this.dnNome = dnNome;
		this.dsCreatoda = dsCreatoda;
		this.dtCreatoil = dtCreatoil;
	}

	/**
	 * Istanzia un nuovo bdl tipo oggetto.
	 *
	 * @param cdTipoOggetto  codice tipo oggetto
	 * @param dnNome  denominazione nome
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 */
	public BdlTipoOggetto(BigDecimal cdTipoOggetto, String dnNome,
			String dsCreatoda, Date dtCreatoil) {
		this.cdTipoOggetto = cdTipoOggetto;
		this.dnNome = dnNome;
		this.dsCreatoda = dsCreatoda;
		this.dtCreatoil = dtCreatoil;
	}

	/**
	 * Istanzia un nuovo bdl tipo oggetto.
	 *
	 * @param cdTipoOggetto  codice tipo oggetto
	 * @param dnNome  denominazione nome
	 * @param dsCatalogo  descrizione catalogo
	 * @param cdCatalogo  codice catalogo
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 * @param dsModificatoda  descrizione modificatoda
	 * @param dtModificatoil  data modificatoil
	 */
	public BdlTipoOggetto(BigDecimal cdTipoOggetto, String dnNome,
			String dsCatalogo,String cdCatalogo, String dsCreatoda, Date dtCreatoil,
			String dsModificatoda, Date dtModificatoil) {
		this.cdTipoOggetto = cdTipoOggetto;
		this.dnNome = dnNome;
		this.dsCatalogo = dsCatalogo;
		this.cdCatalogo = cdCatalogo;
		this.dsCreatoda = dsCreatoda;
		this.dtCreatoil = dtCreatoil;
		this.dsModificatoda = dsModificatoda;
		this.dtModificatoil = dtModificatoil;
	}

	/**
	 * Legge codice tipo oggetto.
	 *
	 * @return the codice tipo oggetto
	 */
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator="BDL_TIPO_OGGETTO_seqgen")
	@SequenceGenerator(name="BDL_TIPO_OGGETTO_seqgen", sequenceName="BDL_TIPO_OGGETTO_SEQ", allocationSize=1)
	@Column(name = "CD_TIPO_OGGETTO", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCdTipoOggetto() {
		return this.cdTipoOggetto;
	}

	/**
	 * Imposta codice tipo oggetto.
	 *
	 * @param cdTipoOggetto the new codice tipo oggetto
	 */
	public void setCdTipoOggetto(BigDecimal cdTipoOggetto) {
		this.cdTipoOggetto = cdTipoOggetto;
	}

	/**
	 * Legge denominazione nome.
	 *
	 * @return the denominazione nome
	 */
	@Column(name = "DN_NOME", nullable = false, length = 100)
	public String getDnNome() {
		return this.dnNome;
	}

	/**
	 * Imposta denominazione nome.
	 *
	 * @param dnNome the new denominazione nome
	 */
	public void setDnNome(String dnNome) {
		this.dnNome = dnNome;
	}

	/**
	 * Legge descrizione catalogo.
	 *
	 * @return the descrizione catalogo
	 */
	@Column(name = "DS_CATALOGO", length = 10)
	public String getDsCatalogo() {
		return this.dsCatalogo;
	}

	/**
	 * Imposta descrizione catalogo.
	 *
	 * @param dsCatalogo the new descrizione catalogo
	 */
	public void setDsCatalogo(String dsCatalogo) {
		this.dsCatalogo = dsCatalogo;
	}

	/**
	 * Legge codice catalogo.
	 *
	 * @return the codice catalogo
	 */
	@Column(name = "CD_CATALOGO", length = 100)
	public String getCdCatalogo() {
		return cdCatalogo;
	}

	/**
	 * Imposta codice catalogo.
	 *
	 * @param cdCatalogo the new codice catalogo
	 */
	public void setCdCatalogo(String cdCatalogo) {
		this.cdCatalogo = cdCatalogo;
	}

}
