package it.lispa.bdl.commons.domain;

import static javax.persistence.GenerationType.SEQUENCE;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * BdlUtente generated by hbm2java.
 */
@Entity
@Table(name = "BDL_UTENTE", uniqueConstraints = @UniqueConstraint(columnNames = "CD_CODICE_FISCALE"))
public class BdlUtente extends BdlDomainBase implements java.io.Serializable {

	/** La Costante serialVersionUID. */
	private static final long serialVersionUID = 5298257636487467280L;
	
	/** codice utente. */
	private BigDecimal cdUtente;
	
	/** codice ruolo. */
	private BigDecimal cdRuolo;
	
	/** nm nome. */
	private String nmNome;
	
	/** cm cognome. */
	private String cmCognome;
	
	/** codice codice fiscale. */
	private String cdCodiceFiscale;
	
	/** denominazione email. */
	private String dnEmail;
	
	/** nr telefono. */
	private String nrTelefono;
	
	/** descrizione stato. */
	private String dsStato;
	
	/** data registrazione. */
	private Date dtRegistrazione;
	
	/** data validazione. */
	private Date dtValidazione;
	
	/**
	 * Istanzia un nuovo bdl utente.
	 */
	public BdlUtente() {
	}

	/**
	 * Istanzia un nuovo bdl utente.
	 *
	 * @param bdlRuolo  bdl ruolo
	 * @param nmNome  nm nome
	 * @param cmCognome  cm cognome
	 * @param cdCodiceFiscale  codice codice fiscale
	 * @param dnEmail  denominazione email
	 * @param dsStato  descrizione stato
	 * @param dtRegistrazione  data registrazione
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 */
	public BdlUtente(BigDecimal bdlRuolo, String nmNome,
			String cmCognome, String cdCodiceFiscale, String dnEmail,
			String dsStato, Date dtRegistrazione, String dsCreatoda,
			Date dtCreatoil) {
		this.cdRuolo = bdlRuolo;
		this.nmNome = nmNome;
		this.cmCognome = cmCognome;
		this.cdCodiceFiscale = cdCodiceFiscale;
		this.dnEmail = dnEmail;
		this.dsStato = dsStato;
		this.dtRegistrazione = dtRegistrazione;
		this.dsCreatoda = dsCreatoda;
		this.dtCreatoil = dtCreatoil;
	}

	/**
	 * Istanzia un nuovo bdl utente.
	 *
	 * @param cdUtente  codice utente
	 * @param bdlRuolo  bdl ruolo
	 * @param nmNome  nm nome
	 * @param cmCognome  cm cognome
	 * @param cdCodiceFiscale  codice codice fiscale
	 * @param dnEmail  denominazione email
	 * @param nrTelefono  nr telefono
	 * @param dsStato  descrizione stato
	 * @param dtRegistrazione  data registrazione
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 */
	public BdlUtente(BigDecimal cdUtente, BigDecimal bdlRuolo, String nmNome,
			String cmCognome, String cdCodiceFiscale, String dnEmail, String nrTelefono,
			String dsStato, Date dtRegistrazione, String dsCreatoda,
			Date dtCreatoil) {
		this.cdUtente = cdUtente;
		this.cdRuolo = bdlRuolo;
		this.nmNome = nmNome;
		this.cmCognome = cmCognome;
		this.cdCodiceFiscale = cdCodiceFiscale;
		this.dnEmail = dnEmail;
		this.nrTelefono = nrTelefono;
		this.dsStato = dsStato;
		this.dtRegistrazione = dtRegistrazione;
		this.dsCreatoda = dsCreatoda;
		this.dtCreatoil = dtCreatoil;
	}

	/**
	 * Istanzia un nuovo bdl utente.
	 *
	 * @param cdUtente  codice utente
	 * @param cdRuolo  codice ruolo
	 * @param nmNome  nm nome
	 * @param cmCognome  cm cognome
	 * @param cdCodiceFiscale  codice codice fiscale
	 * @param dnEmail  denominazione email
	 * @param nrTelefono  nr telefono
	 * @param dsStato  descrizione stato
	 * @param dtRegistrazione  data registrazione
	 * @param dtValidazione  data validazione
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 * @param dsModificatoda  descrizione modificatoda
	 * @param dtModificatoil  data modificatoil
	 */
	public BdlUtente(BigDecimal cdUtente, BigDecimal cdRuolo, String nmNome,
			String cmCognome, String cdCodiceFiscale, String dnEmail,
			String nrTelefono, String dsStato, Date dtRegistrazione,
			Date dtValidazione, String dsCreatoda, Date dtCreatoil,
			String dsModificatoda, Date dtModificatoil) {
		this.cdUtente = cdUtente;
		this.cdRuolo = cdRuolo;
		this.nmNome = nmNome;
		this.cmCognome = cmCognome;
		this.cdCodiceFiscale = cdCodiceFiscale;
		this.dnEmail = dnEmail;
		this.nrTelefono = nrTelefono;
		this.dsStato = dsStato;
		this.dtRegistrazione = dtRegistrazione;
		this.dtValidazione = dtValidazione;
		this.dsCreatoda = dsCreatoda;
		this.dtCreatoil = dtCreatoil;
		this.dsModificatoda = dsModificatoda;
		this.dtModificatoil = dtModificatoil;
	}

	
	/**
	 * Legge codice utente.
	 *
	 * @return the codice utente
	 */
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator="BDL_UTENTE_seqgen")
	@SequenceGenerator(name="BDL_UTENTE_seqgen", sequenceName="BDL_UTENTE_SEQ", allocationSize=1)
	@Column(name = "CD_UTENTE", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCdUtente() {
		return this.cdUtente;
	}
	
	/**
	 * Imposta codice utente.
	 *
	 * @param cdUtente the new codice utente
	 */
	public void setCdUtente(BigDecimal cdUtente) {
		this.cdUtente = cdUtente;
	}
	
	/**
	 * Legge codice ruolo.
	 *
	 * @return the codice ruolo
	 */
	@Column(name = "CD_RUOLO", nullable = false, precision = 31, scale = 0)
	public BigDecimal getCdRuolo() {
		return this.cdRuolo;
	}

	/**
	 * Imposta codice ruolo.
	 *
	 * @param cdRuolo the new codice ruolo
	 */
	public void setCdRuolo(BigDecimal cdRuolo) {
		this.cdRuolo = cdRuolo;
	}

	/**
	 * Legge nm nome.
	 *
	 * @return the nm nome
	 */
	@Column(name = "NM_NOME", nullable = false, length = 50)
	public String getNmNome() {
		return this.nmNome;
	}

	/**
	 * Imposta nm nome.
	 *
	 * @param nmNome the new nm nome
	 */
	public void setNmNome(String nmNome) {
		this.nmNome = nmNome;
	}

	/**
	 * Legge cm cognome.
	 *
	 * @return the cm cognome
	 */
	@Column(name = "CM_COGNOME", nullable = false, length = 50)
	public String getCmCognome() {
		return this.cmCognome;
	}

	/**
	 * Imposta cm cognome.
	 *
	 * @param cmCognome the new cm cognome
	 */
	public void setCmCognome(String cmCognome) {
		this.cmCognome = cmCognome;
	}

	/**
	 * Legge codice codice fiscale.
	 *
	 * @return the codice codice fiscale
	 */
	@Column(name = "CD_CODICE_FISCALE", unique = true, nullable = false, length = 16)
	public String getCdCodiceFiscale() {
		return this.cdCodiceFiscale;
	}

	/**
	 * Imposta codice codice fiscale.
	 *
	 * @param cdCodiceFiscale the new codice codice fiscale
	 */
	public void setCdCodiceFiscale(String cdCodiceFiscale) {
		this.cdCodiceFiscale = cdCodiceFiscale;
	}

	/**
	 * Legge denominazione email.
	 *
	 * @return the denominazione email
	 */
	@Column(name = "DN_EMAIL", nullable = false, length = 50)
	public String getDnEmail() {
		return this.dnEmail;
	}

	/**
	 * Imposta denominazione email.
	 *
	 * @param dnEmail the new denominazione email
	 */
	public void setDnEmail(String dnEmail) {
		this.dnEmail = dnEmail;
	}

	/**
	 * Legge nr telefono.
	 *
	 * @return the nr telefono
	 */
	@Column(name = "NR_TELEFONO", length = 50)
	public String getNrTelefono() {
		return this.nrTelefono;
	}

	/**
	 * Imposta nr telefono.
	 *
	 * @param nrTelefono the new nr telefono
	 */
	public void setNrTelefono(String nrTelefono) {
		this.nrTelefono = nrTelefono;
	}

	/**
	 * Legge descrizione stato.
	 *
	 * @return the descrizione stato
	 */
	@Column(name = "DS_STATO", nullable = false, length = 50)
	public String getDsStato() {
		return this.dsStato;
	}

	/**
	 * Imposta descrizione stato.
	 *
	 * @param dsStato the new descrizione stato
	 */
	public void setDsStato(String dsStato) {
		this.dsStato = dsStato;
	}

	/**
	 * Legge data registrazione.
	 *
	 * @return the data registrazione
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_REGISTRAZIONE", nullable = false)
	public Date getDtRegistrazione() {
		return this.dtRegistrazione;
	}

	/**
	 * Imposta data registrazione.
	 *
	 * @param dtRegistrazione the new data registrazione
	 */
	public void setDtRegistrazione(Date dtRegistrazione) {
		this.dtRegistrazione = dtRegistrazione;
	}

	/**
	 * Legge data validazione.
	 *
	 * @return the data validazione
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DT_VALIDAZIONE")
	public Date getDtValidazione() {
		return this.dtValidazione;
	}

	/**
	 * Imposta data validazione.
	 *
	 * @param dtValidazione the new data validazione
	 */
	public void setDtValidazione(Date dtValidazione) {
		this.dtValidazione = dtValidazione;
	}
}
