package it.lispa.bdl.commons.domain;

// Generated 29-nov-2013 10.47.17 by Hibernate Tools 3.6.0

import static javax.persistence.GenerationType.SEQUENCE;

import java.math.BigDecimal;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

/**
 * BdlWorkFilesystem generated by hbm2java.
 */
@Entity
@Table(name = "BDL_WORK_FILESYSTEM")
public class BdlWorkFilesystem implements java.io.Serializable {

	/** La Costante serialVersionUID. */
	private static final long serialVersionUID = 4872549255772901643L;
	
	/** codice work filesystem. */
	private BigDecimal cdWorkFilesystem;
	
	/** location. */
	private String dsLocation;

	/** flag in uso. */
	private Boolean flInUso;
	
	/**
	 * Istanzia un nuovo bdl tipo oggetto.
	 */
	public BdlWorkFilesystem() {
	}

	/**
	 * Istanzia un nuovo oggetto.
	 *
	 * @param dsLocation  location
	 * @param flInUso  flag in uso
	 */
	public BdlWorkFilesystem(String dsLocation, Boolean flInUso) {
		this.dsLocation = dsLocation;
		this.flInUso = flInUso;
	}

	/**
	 * Istanzia un nuovo bdl tipo oggetto.
	 *
	 * @param cdWorkFilesystem  codice 
	 * @param dsLocation  location
	 * @param flInUso  flag in uso
	 * @param dsCreatoda  descrizione creatoda
	 * @param dtCreatoil  data creatoil
	 * @param dsModificatoda  descrizione modificatoda
	 * @param dtModificatoil  data modificatoil
	 */
	public BdlWorkFilesystem(BigDecimal cdWorkFilesystem, String dsLocation, Boolean flInUso) {
		this.cdWorkFilesystem = cdWorkFilesystem;
		this.dsLocation = dsLocation;
		this.flInUso = flInUso;
	}
	
	/**
	 * Legge codice.
	 *
	 * @return the codice
	 */
	@Id
	@GeneratedValue(strategy = SEQUENCE, generator="BDL_WORK_FILESYSTEM_seqgen")
	@SequenceGenerator(name="BDL_WORK_FILESYSTEM_seqgen", sequenceName="BDL_WORK_FILESYSTEM_SEQ", allocationSize=1)
	@Column(name = "CD_WORK_FILESYSTEM", unique = true, nullable = false, precision = 31, scale = 0)
	public BigDecimal getCdWorkFilesystem() {
		return this.cdWorkFilesystem;
	}

	/**
	 * Imposta codice.
	 *
	 * @param cdWorkFilesystem the new codice
	 */
	public void setCdWorkFilesystem(BigDecimal cdWorkFilesystem) {
		this.cdWorkFilesystem = cdWorkFilesystem;
	}

	/**
	 * Legge location.
	 *
	 * @return the location
	 */
	@Column(name = "DS_LOCATION", nullable = false, length = 200)
	public String getDsLocation() {
		return this.dsLocation;
	}

	/**
	 * Imposta location.
	 *
	 * @param dsLocation the new location
	 */
	public void setDsLocation(String dsLocation) {
		this.dsLocation = dsLocation;
	}

	/**
	 * Legge flag pdf multipagina.
	 *
	 * @return the flag pdf multipagina
	 */
	@Column(name = "FL_INUSO", nullable = false)
	@Type(type="true_false")
	public Boolean getFlInUso() {
		return flInUso;
	}

	/**
	 * Imposta flag in uso.
	 *
	 * @param flInUso the new flag in uso
	 */
	public void setFlInUso(Boolean flInUso) {
		this.flInUso = flInUso;
	}
	
}
